# Generated by Django 4.2.11 on 2025-10-05 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='autocarros.sector'),
        ),
    ]
