# Generated by Django 4.2.11 on 2025-10-05 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0002_customuser_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectores_geridos', to=settings.AUTH_USER_MODEL),
        ),
    ]
