# Generated by Django 4.2.11 on 2025-10-06 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0003_sector_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='associados',
            field=models.ManyToManyField(blank=True, related_name='sectores_associados', to=settings.AUTH_USER_MODEL),
        ),
    ]
