# Generated by Django 5.2.7 on 2025-10-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('autocarros', '0004_sector_associados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sector',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('user', 'Usuário')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
