# Generated by Django 5.2.7 on 2025-10-24 08:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0005_remove_customuser_data_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobradorViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('passageiros', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('nota_validacao', models.TextField(blank=True, null=True)),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('autocarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_cobrador', to='autocarros.autocarro')),
                ('cobrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_validas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-hora', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ultima', models.DateField(help_text='Data da última manutenção realizada')),
                ('km_ultima', models.PositiveIntegerField(help_text='Km na última manutenção')),
                ('km_proxima', models.PositiveIntegerField(help_text='Km previsto para próxima manutenção')),
                ('oleo_motor', models.BooleanField(default=False)),
                ('oleo_diferencial', models.BooleanField(default=False)),
                ('oleo_cambio', models.BooleanField(default=False)),
                ('filtro_combustivel', models.BooleanField(default=False)),
                ('filtro_oleo', models.BooleanField(default=False)),
                ('filtro_ar', models.BooleanField(default=False)),
                ('km_prox_oleo_motor', models.PositiveIntegerField(blank=True, help_text='Km previsto para próxima troca do óleo do motor', null=True)),
                ('km_prox_oleo_diferencial', models.PositiveIntegerField(blank=True, help_text='Km previsto para próxima troca do óleo do diferencial', null=True)),
                ('km_prox_oleo_cambio', models.PositiveIntegerField(blank=True, help_text='Km previsto para próxima troca do óleo do câmbio', null=True)),
                ('km_prox_filtro_combustivel', models.PositiveIntegerField(blank=True, help_text='Km previsto para troca do filtro de combustível', null=True)),
                ('km_prox_filtro_oleo', models.PositiveIntegerField(blank=True, help_text='Km previsto para troca do filtro de óleo', null=True)),
                ('km_prox_filtro_ar', models.PositiveIntegerField(blank=True, help_text='Km previsto para troca do filtro de ar', null=True)),
                ('custo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_progresso', 'Em Progresso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autocarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='autocarros.autocarro')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_responsavel', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='autocarros.sector')),
            ],
            options={
                'ordering': ['-data_ultima', '-criado_em'],
            },
        ),
    ]
