# Generated by Django 5.2.7 on 2025-10-24 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0006_cobradorviagem_manutencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registo', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_km', to='autocarros.sector')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroKMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_atual', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autocarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='autocarros.autocarro')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='autocarros.registrokm')),
            ],
            options={
                'unique_together': {('registro', 'autocarro')},
            },
        ),
    ]
