# Generated by Django 5.2.7 on 2025-10-25 08:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0007_registrokm_registrokmitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_deposito', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='autocarros.sector')),
            ],
            options={
                'ordering': ['-data_deposito', '-criado_em'],
            },
        ),
    ]
