# Generated by Django 5.2.7 on 2025-10-26 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0008_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('salario', 'Salários por sector'), ('fundo_maneio', 'Fundo de maneio por sector'), ('cameras', 'Carregamento das câmaras'), ('gps', 'Carregamento de GPS'), ('internet_tv', 'Internet/TV do escritório'), ('outro', 'Outro')], max_length=32)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('periodicidade', models.CharField(default='mensal', help_text='mensal|anual|único', max_length=32)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_fixas', to='autocarros.sector')),
            ],
            options={
                'verbose_name': 'Despesa Fixa',
                'verbose_name_plural': 'Despesas Fixas',
                'ordering': ['-ativo', 'sector', 'categoria'],
            },
        ),
    ]
