# Generated by Django 5.2.7 on 2025-10-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0009_despesafixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriosector',
            name='despesa_geral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despesa geral do setor'),
        ),
    ]
