# Generated by Django 5.2.7 on 2025-11-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0010_relatoriosector_despesa_geral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='km_prox_filtro_ar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Km previsto para troca do filtro de ar', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='km_prox_filtro_combustivel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Km previsto para troca do filtro de combustível', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='km_prox_filtro_oleo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Km previsto para troca do filtro de óleo', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='km_prox_oleo_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Km previsto para próxima troca do óleo do câmbio', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='km_prox_oleo_diferencial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Km previsto para próxima troca do óleo do diferencial', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='km_prox_oleo_motor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Km previsto para próxima troca do óleo do motor', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='km_proxima',
            field=models.DecimalField(decimal_places=2, help_text='Km previsto para próxima manutenção', max_digits=14),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='km_ultima',
            field=models.DecimalField(decimal_places=2, help_text='Km na última manutenção', max_digits=14),
        ),
    ]
