# Generated by Django 4.2.11 on 2026-01-29 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocarros', '0011_alter_manutencao_km_prox_filtro_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('FIXA', 'Despesa Fixa'), ('VARIAVEL', 'Despesa Variável')], max_length=20, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesa',
            },
        ),
        migrations.AlterField(
            model_name='despesafixa',
            name='categoria',
            field=models.CharField(choices=[('salario', 'Salários'), ('fundo_maneio', 'Fundo De Maneio'), ('subsidio_alimentacao', 'Subsídio de Alimentação'), ('cameras', 'Carregamento das Câmaras'), ('gps', 'Carregamento de GPS'), ('internet_tv', 'Internet/TV do Escritório'), ('agua_luz', 'Água e Luz'), ('prestacao', 'Prestação dos Autocarros'), ('seguro', 'Seguro das Viaturas'), ('outro', 'Outro')], max_length=32),
        ),
        migrations.CreateModel(
            name='SubCategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='autocarros.categoriadespesa')),
            ],
            options={
                'verbose_name': 'Subcategoria de Despesa',
                'verbose_name_plural': 'Subcategorias de Despesa',
                'ordering': ['categoria', 'nome'],
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Despesa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autocarros.categoriadespesa')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='autocarros.subcategoriadespesa')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data'],
            },
        ),
    ]
